# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'LUMEvents' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LUMEvents
    pod 'Parse'
    pod 'ParseUI'

  target 'LUMEventsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LUMEventsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
